@startuml

skinparam componentStyle uml2

package "'RegistroCompra' Aggregate" <<Rectangle>> {
	class RegistroCompra <<(A,#fffab8) Aggregate Root>> {
		LocalDateTime dataHoraRealizacao
		RegistroCompraId id
		CompraId compra
		ClienteId cliente
	}
	class RegistroCompraId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
	class RegistroCompraService <<(S,DarkSeaGreen) Service>> {
		void RegistrarCompra(CompraId compraId, ClienteId clienteId)
	}
}
RegistroCompra --> RegistroCompraId : id
legend left
  This bounded context implements the subdomain 'Controle'.
end legend


@enduml
